In [2]:
from datetime import datetime

# Include Cell ID

In [5]:
def calculate_ct(start_date, end_date):
    # Convert start and end dates to datetime objects
    start_datetime = datetime.strptime(start_date, "%H:%M:%S %d %b %Y")
    end_datetime = datetime.strptime(end_date, "%H:%M:%S %d %b %Y")

    # Define the start and end years for the range
    start_year = 2019
    end_year = 2020

    # Define the start and end dates within the specified year range
    start_date_within_range = datetime(start_year, 12, 1)
    end_date_within_range = datetime(end_year, 5, 31)

    # Calculate the day values based on the adjusted start and end dates
    start_day = (start_datetime - start_date_within_range).days
    end_day = (end_datetime - start_date_within_range).days

    # Calculate the start and end minutes within a day
    start_minute = start_datetime.hour * 60 + start_datetime.minute
    end_minute = end_datetime.hour * 60 + end_datetime.minute

    # Adjust the start and end minutes if the seconds are greater than or equal to 30
    if start_datetime.second >= 30:
        start_minute += 1

    if end_datetime.second >= 30:
        end_minute += 1

    # Calculate the length by subtracting the start minute from the end minute
    length = end_minute - start_minute

    # Construct the output list with day values, start and end minutes, and length
    ct = [start_day, start_minute, end_day, end_minute, length]
    return ct


# Data containing the ID, start date, and end date
data = [
    (1, "08:12:28 13 Mar 2020", "09:06:36 13 Mar 2020"),
    (2, "09:12:48 13 Mar 2020", "09:58:16 13 Mar 2020"),
    (3, "10:00:12 13 Mar 2020", "10:11:56 13 Mar 2020"),
    (4, "10:14:32 13 Mar 2020", "10:29:00 13 Mar 2020"),
    (5, "10:22:40 13 Mar 2020", "10:46:56 13 Mar 2020"),
    (6, "10:42:32 13 Mar 2020", "10:59:04 13 Mar 2020"),
    (7, "11:00:32 13 Mar 2020", "11:32:28 13 Mar 2020"),
    (8, "11:30:44 13 Mar 2020", "11:51:52 13 Mar 2020"),
    (9, "11:48:08 13 Mar 2020", "12:09:04 13 Mar 2020"),
    (10, "12:03:08 13 Mar 2020", "12:38:04 13 Mar 2020"),
    (11, "12:32:48 13 Mar 2020", "13:14:32 13 Mar 2020"),
    (12, "13:53:00 13 Mar 2020", "14:05:16 13 Mar 2020"),
    (13, "14:03:28 13 Mar 2020", "14:31:20 13 Mar 2020"),
    (14, "15:09:36 13 Mar 2020", "15:45:20 13 Mar 2020"),
    (15, "15:48:00 13 Mar 2020", "16:12:44 13 Mar 2020"),
    (16, "16:12:00 13 Mar 2020", "16:33:44 13 Mar 2020"),
    (17, "16:29:40 13 Mar 2020", "16:38:20 13 Mar 2020"),
    (18, "16:44:24 13 Mar 2020", "17:13:32 13 Mar 2020"),
    (19, "17:12:56 13 Mar 2020", "17:45:48 13 Mar 2020"),
    (20, "18:10:04 13 Mar 2020", "18:28:04 13 Mar 2020"),
    (21, "18:27:28 13 Mar 2020", "18:50:04 13 Mar 2020"),
    (22, "19:15:32 13 Mar 2020", "19:54:00 13 Mar 2020"),
    (23, "19:47:12 13 Mar 2020", "20:15:52 13 Mar 2020"),
    (24, "20:14:12 13 Mar 2020", "20:48:12 13 Mar 2020"),
    (25, "20:48:36 13 Mar 2020", "21:21:40 13 Mar 2020"),
    (26, "21:27:40 13 Mar 2020", "21:50:48 13 Mar 2020"),
    (27, "21:48:20 13 Mar 2020", "22:13:00 13 Mar 2020"),
    (28, "22:28:24 13 Mar 2020", "23:00:00 13 Mar 2020"),
    (29, "23:38:56 13 Mar 2020", "00:16:28 14 Mar 2020"),
    (30, "00:13:24 14 Mar 2020", "00:30:44 14 Mar 2020"),
    (31, "01:06:40 14 Mar 2020", "01:24:08 14 Mar 2020"),
    (32, "02:19:20 14 Mar 2020", "02:34:36 14 Mar 2020"),
    (33, "02:43:24 14 Mar 2020", "03:12:44 14 Mar 2020"),
    (34, "03:17:16 14 Mar 2020", "03:41:20 14 Mar 2020"),
    (35, "03:57:16 14 Mar 2020", "04:31:56 14 Mar 2020"),
    (36, "04:27:40 14 Mar 2020", "04:50:20 14 Mar 2020"),
    (37, "04:49:56 14 Mar 2020", "05:19:48 14 Mar 2020")
]


# Iterate through each row and generate the results
for row in data:
    id = row[0]
    start_date = row[1]
    end_date = row[2]

    ct = calculate_ct(start_date, end_date)
    result = [id] + ct
    results =  ct
    print(results)

[103, 492, 103, 547, 55]
[103, 553, 103, 598, 45]
[103, 600, 103, 612, 12]
[103, 615, 103, 629, 14]
[103, 623, 103, 647, 24]
[103, 643, 103, 659, 16]
[103, 661, 103, 692, 31]
[103, 691, 103, 712, 21]
[103, 708, 103, 729, 21]
[103, 723, 103, 758, 35]
[103, 753, 103, 795, 42]
[103, 833, 103, 845, 12]
[103, 843, 103, 871, 28]
[103, 910, 103, 945, 35]
[103, 948, 103, 973, 25]
[103, 972, 103, 994, 22]
[103, 990, 103, 998, 8]
[103, 1004, 103, 1034, 30]
[103, 1033, 103, 1066, 33]
[103, 1090, 103, 1108, 18]
[103, 1107, 103, 1130, 23]
[103, 1156, 103, 1194, 38]
[103, 1187, 103, 1216, 29]
[103, 1214, 103, 1248, 34]
[103, 1249, 103, 1282, 33]
[103, 1288, 103, 1311, 23]
[103, 1308, 103, 1333, 25]
[103, 1348, 103, 1380, 32]
[103, 1419, 104, 16, -1403]
[104, 13, 104, 31, 18]
[104, 67, 104, 84, 17]
[104, 139, 104, 155, 16]
[104, 163, 104, 193, 30]
[104, 197, 104, 221, 24]
[104, 237, 104, 272, 35]
[104, 268, 104, 290, 22]
[104, 290, 104, 320, 30]

In [ ]:
#